services:
  plexbridge-app:
    image: ghcr.io/vandaahl/plexbridge:latest
    restart: unless-stopped
    volumes:
      - ./logs:/app/var/log
      - ./database:/app/var/database/data.db
    environment:
      # Port in URL must match port assigned to nginx
      - TRAKT_REDIRECT_URL=http://localhost:8000/redirect
      - TZ=Europe/Amsterdam
      - APP_SECRET
    ports:
      - "8000:8080"
    secrets:
      - trakt_client_id
      - trakt_client_secret
      - letterboxd_cookie_user_value
      - letterboxd_cookie_csrf_value

secrets:
  trakt_client_id:
    file: secrets/trakt_client_id.txt
  trakt_client_secret:
    file: secrets/trakt_client_secret.txt
  letterboxd_cookie_user_value:
    file: secrets/letterboxd_cookie_user_value.txt
  letterboxd_cookie_csrf_value:
    file: secrets/letterboxd_cookie_csrf_value.txt
