services:
  # The nginx container expects this service to be called plexbridge-app, changing the name it will break things (use container_name key instead)
  plexbridge-app:
    image: ghcr.io/vandaahl/plexbridge:latest
    restart: unless-stopped
    working_dir: /app
    volumes:
      - app-data:/app
    environment:
      # Port in URL must match port assigned to nginx
      - TRAKT_REDIRECT_URL=http://localhost:8000/redirect
      - TZ=Europe/Amsterdam
    secrets:
      - trakt_client_id
      - trakt_client_secret
      - letterboxd_cookie_user_value
      - letterboxd_cookie_csrf_value

  plexbridge-nginx:
    image: cgr.dev/chainguard/nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - app-data:/app:ro
    user: root
    entrypoint: ["nginx"]
    command: ["-g", "daemon off;", "-c", "/app/nginx.conf"]

secrets:
  trakt_client_id:
    file: secrets/trakt_client_id.txt
  trakt_client_secret:
    file: secrets/trakt_client_secret.txt
  letterboxd_cookie_user_value:
    file: secrets/letterboxd_cookie_user_value.txt
  letterboxd_cookie_csrf_value:
    file: secrets/letterboxd_cookie_csrf_value.txt

volumes:
  app-data: